apiVersion: v1
kind: Service
metadata:
  name: sprongbootapp-service
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 49161
      targetPort: 8080
      nodePort: 30001
  selector:
    app: sprongbootapp
