apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
        - image: oad3jp999/application-springboot:@tag@
          name: springbootapp
          ports:
            - containerPort: 8080
      restartPolicy: Always
