apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-springboot-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-springboot-app
  template:
    metadata:
      labels:
        app: application-springboot-app
    spec:
      containers:
        - image: oad3jp999/application-springboot:@tag@
          name: application-springboot
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: application-springboot-cm
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: application-springboot-service
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 49161
      targetPort: 8080
      nodePort: 30001
  selector:
    app: application-springboot-app
